package com.rtxschool.zombies;

import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.os.AsyncTask;
import android.widget.ImageView;

import java.io.InputStream;
import java.util.ArrayList;

public class zombie_list {
    public static
    String[][] zombies =
            {
                    {"Night of the Comet", "1984", "", "https://cdn.collider.com/wp-content/uploads/2016/10/night-of-comet.jpg", "What would kids in the 1980s do if the apocalypse blew through the world without them noticing? Hang out at the mall, but of course. Thatâ€™s the set -up for this very funny, quite dated horror -comedy, which begins when a quartet of adolescents themselves inside a projection booth at the mallâ€™s multiplex. This somehow allows them to live through an extinction level event of some sort, which has also left roaming bands of murderous mutants. Catherine Mary Stewart of the equally inexplicable Weekend at Bernieâ€™s leads the film, but itâ€™s a movie of mood more than substance ultimately. Does the wealth -"},
                    {"Dead Snow", "200?", "Tommy Wirkola", "https://cdn.ctheir belongingsollider.com/wp-content/uploads/2016/07/dead-snow.jpg", "With so many zombie movies over the years, eventually youâ€™re going to run out of ways to freshen up the sub -genre. Enter Wirkolaâ€™s decidedly skewed take on zombies in this horror -comedy with plenty of guts. Sure, zombies are great movie monsters, but if you have Nazi zombies, well youâ€™ve just doubled -down on the level of villainy (and pun -worthiness) in your picture! This splatter -"},
                    {"28 Weeks Later", "200?", "Juan Carlos Fresnadillo", "https://cdn.collider.com/wp-content/uploads/2015/08/28-weeks-later.jpg", "28 Weeks Later is one of those rare sequels that does the original proud, especially when the original is a film as acclaimed and influential as 28 Days Later. Director Juan Carlos Fresnadillo made his English -language directorial debut on the sequel, stepping in for Danny Boyle, and pulled off a fantastic in honoring the â€œfranchise styleâ€ Boyle established in the original â€” the edits and snarling infected â€” while evolving it and adding his own visual flourish to the mix. 28 Days Later subverted the conventions of the zombie genre in such clever, convincing ways, it became the modern day zombie template that countless films tried to mimic. 28 Weeks Later was smart enough not to follow the blueprint and flipped the script, depicting the British governmentâ€™s attempt to rebuild society in the aftermath of the rage virus and the subsequent outbreak that brings it all crashing down. Through the contained military facility we get to witness a small -"},
                    {"Night of the Creeps", "1986", "", "https://cdn.collider.com/wp-content/uploads/2017/10/night-of-the-creeps.jpg", "The delightfully delirious directorial debut from Monster Squad helmer Fred Night of the Creeps is a loving tribute to the zombie genre thatâ€™s as to the brim with self -reference as it is with cheeky, cheesy fun. The film follows two college boys trying to land a spot in a fraternity in the name of scoring To earn their initiation, the boys have to sneak into the college medical center, where they discover the long -frozen corpse of a 19s coed with alien slugs coursing through his brain. Hijinks follow, the body thaws, and space parasites are unleashed on campus, transforming their hosts into mindless zombies. A blunt -force display of sensibilities, Night of the Creeps is an exuberant blend of zombie genre trappings and the sci -fi B -"},
                    {"ParaNorman", "2012", "Chris Butler, Sam Fell", "https://cdn.collider.com/wp-content/uploads/paranorman-movie-image.jpg", "Rarely do zombies get the animated treatment (rarer still, stop -motion animation), and even if they do, theyâ€™re traditionally made the villains. LAIKA is anything but traditional, which makes their films so endearing, unique, and memorable. ParaNorman, one of the stop -motion studioâ€™s handful of original films, manages to not only (re)animate some truly gruesome and decaying corpses, but to give them a voice and agency within the story. Most live -action movies canâ€™t even achieve that much. But what truly makes ParaNorman a great zombie tale is that the zombies themselves are more than just part of the spooky story (along with witches, ghosts, and dark magic), theyâ€™re a similar stand -"},
                    {"Zombieland", "200?", "Ruben Fleischer", "https://cdn.collider.com/wp-content/uploads/Zombieland-movie-image-Woody-Harrelson-Jesse-Eisenberg-1.jpg", "One of the greatest enjoyments of horror cinema in the last few decades has been watching filmmakers who grew up knowing the rules of the genre find new and exciting ways to subvert them. Shaun of the Dead is the gold star of self -referential cinematic love letters, but Ruben Fleischerâ€™s Zombieland is a comedy horror in its own right. Zombieland arrived in theaters in 200?, towards the end of a new zombie boom, and itâ€™s a film made for audiences who already know the rules and want to have some fun playing the game. The script comes from Deadpool screenwriters Reese and and both properties share the duoâ€™s for genre deconstruction and razor -sharp, smart -mouthed humor. The ensemble comedic performers has a blast doling out verbal beatdowns in between actually beating down the undead. And letâ€™s be honest â€” even if Zombieland wasnâ€™t an all -"},
                    {"Planet Terror", "200?", "Robert Rodriguez", "https://cdn.collider.com/wp-content/uploads/rose_mcgowan_and_marley_shelton_star_in_robert_rodriquez_s_planet_terror_grindhouse_s.jpg", "In the tradition of Romero, modern Zombie films have become known as the home of sharp social commentary and forward -thinking humanism. You wonâ€™t find any of that in Planet Terror. Initially released as one half of the Robert Rodriguez/Quentin Tarantino double feature Grindhouse, Planet Terror was initially dismissed by critics as the lesser of the two entries, but time has proven it to be a raucous, endlessly rewatchable, and consummately reprobate entry to the zombie genre.Written and directed by Rodriguez (though cast interviews revealed that the directors collaborated freely on both pictures), Planet Terror is cheeky, free -wheeling, and delighted with its own depravity as it employs the shield of grindhouse tropes to through horror taboos from child death to testicular violence. Borrowing heavily from the exploitation aesthetic with the kind of budget its forbears could only dream of, the film stars Rose McGowan as Cherry Darling, a brassy go -go dancer who finds herself in the midst of the apocalypse with a rag -tag band of survivors â€” played by an A+ ensemble of underrated actors who finally get to play the leading roles theyâ€™ve always deserved. Flesh -hungry humanoid mutants tear through the Texas countryside, leaving a gooey trail of body parts in their wake. In short order, Cherry winds up with a machine gun for a leg, as you do, and the film boils over into a chaotic free -for -"},
                    {"Train to Busan", "2016", "Sang-ho Yen", "https://cdn.collider.com/wp-content/uploads/2016/12/train-to-busan-movie-image.jpg", "After the zombie genre got a big boost in the early aughts, the living dead thrived on serialized television but they died off in cinemas for a while. Train to Busan is a proper return to form for the genre, an old -fashioned zombie drama with heart and soul, a simple but clever set -up and some scary af zombies. The film follows a father and his young daughter on a terrifying train ride that sends them speeding through a zombie outbreak in South Korea, trapped inside increasingly infected compartments of the passenger train. Filled with characters you root for â€” and some you love to root against â€” Train to Busan is with zombie action that uses the tight quarters to thrilling effect, traveling through the cars of the train with a series of imaginative set -pieces that put the physicality of these contorted, fast -"},
                    {"The Beyond", "1981", "Lucio Fulci", "https://cdn.collider.com/wp-content/uploads/2017/10/the-beyond.jpg", "After making his answer to the Romero school of zombie cinema with Zombi 2, Italian horror maestro Lucio Fulci took the idea of the undead and got weird with it in his unofficial â€œGates of Hellâ€ trilogy; City of the Living Dead, The Beyond, and House by the Cemetary. The Beyond has proven the most enduring of the lot, and for good reason, itâ€™s a hypnotic oddity, as unsettling as it is incoherent. If you walk into The Beyond assuming the plot matters (it really doesnâ€™t), the film follows a young woman (MacColl), who inherits a Louisianna hotel that, bad news, happens to be built on one of the gates to hell. In between the eye -gouging, acid face -"},
                    {"Day of the Dead", "1985", "George Romero", "https://cdn.collider.com/wp-content/uploads/2017/10/day-of-the-dead.jpg", "The concluding chapter in Romeroâ€™s original â€œDeadâ€ trilogy, Day of the Dead has never found the frenzied fans of its two predecessors. In fact, itâ€™s often been met with some harsh criticisms, which is unfortunate because itâ€™s a staggering zombie film in its own right. Perhaps its the idea of sentient zombies, a tenet of Romeroâ€™s later â€œDeadâ€ films introduced in Day of the Dead via Bub, the loveable flesh -hungry fiend who begins to show signs of cognizance during military testing. Or maybe itâ€™s the script, which turns up the volume on Romeroâ€™s trademark cultural critique until the skewering tips over into preachy territory. But hereâ€™s the thing, while other filmmakers may have been happy to recreate the formula that worked for them in the past, Romero consistently evolved his living dead films, and Day of the Dead was the boldest of them all. Set on a military base, Romero gets downright political, asking hard questions about power and how much any one organization should or can ever have. Itâ€™s a pensive film, not quite as primal as Night of the Living Dead and nowhere near as funny as Dawn of the Dead, which makes it a slow watch. But hoo boy, if you came for zombie gore, is the payoff rewarding. Day of the Dead has some of the most stomach -"},
                    {"Dawn of the Dead", "2004", "", "https://cdn.collider.com/wp-content/uploads/2016/10/dawn-of-the-dead.jpg", "These days, Snyder is known for being the architect of action movie universe, but it was not always that way. Before Man of Steel, Watchmen, or even his claim to fame 300, Snyder turned in a terrifying modernized account of Romeroâ€™s 1978 original by the same name. (Oddly enough, Marvel movie -"},
                    {"Return of the Living Dead", "1985", "Dan O'Bannon", "https://cdn.collider.com/wp-content/uploads/return_of_the_living_dead_movie_image_01.jpg", "Blood, boobs, and braaaaaiiiiins; The Return of the Living Dead is the triple threat of zombie B -movies and itâ€™s without a doubt the most fun you can have hanging with the undead. After a pair of fumbling medical warehouse employees accidentally unleash a toxic gas on a nearby cemetery, the dead return to life in ghoulish, grizzly fashion with an insatiable hunger for brains. The directorial debut from Alien and Total Recall screenwriter Dan Oâ€™Bannon, Return of the Living Dead is a zombie film and a party rolled into one mud -smeared, punk romp. Long before the meta -horror trend, Return of the Living dead name -dropped its inspiration openly, casually referencing Night of the Living Dead without abandon. Itâ€™s an outrageous film from start to finish, including iconic moments like Linnea Quigleyâ€™s nude grave dancing, a morose talking zombie, and slimy, gory creature effects that make you want to take a shower. Return of the Living Dead is over -the -top and gleefully tongue -in -cheek, like an E.C. comic come to life, a hard -"},
                    {"Dead Alive", "1992", "", "https://cdn.collider.com/wp-content/uploads/2016/04/dead-alive.jpg", "Peter could have only made this gory, gushy, and occasionally outright repulsive zombie film, and he would still be a kind of legend, if not at the level of the man who brought Lord of the Rings to the big -screen. Dead Alive openly toys with one of horrorâ€™s most cherished concepts â€“ repression â€“ and when Lionelâ€™s (Balme) love for a local girl is no longer held down by his controlling mother (Moody), out come the decaying zombie -like creatures to act as a horrifying expression of mommaâ€™s villainous control. Like Tobe Hooper and Stuart Gordonâ€™s iconic 1980s output, Dead Alive (also known as Braindead) strives for what Hooper called â€œred humor,â€ a melding of and physical comedy with horror, and the result is the most idiosyncratic and zany effort that produced, complete with zombie -"},
            };

    public static
    ArrayList<zombie_p> zombie_coll = get_coll();

    static ArrayList<zombie_p> get_coll() {

        ArrayList<zombie_p> zombiez = new ArrayList<zombie_p>();

        int count = zombie_list.zombies.length;

        for (int i = 0; i < count; i++
        ) {
            zombie_p r = new zombie_p(zombie_list.zombies[i][0], zombie_list.zombies[i][1], zombie_list.zombies[i][2], zombie_list.zombies[i][3], zombie_list.zombies[i][4].replaceAll("â€™", "'")
            );

            zombiez.add(r);

            //      new get_net_img(r.bmp).execute(r.img_url);
        }
        //  return zombiez;
        return zombiez;
    }

    public static zombie_p get_by_movie(String movie
    ) {
        int count = zombie_coll.size();

        for (int i = 0; i < count; i++
        ) {
            zombie_p tmp = zombie_coll.get(i);
            if (tmp.nomencl.equals(movie)
            ) {
                return tmp;
            }
        }
        return null;
    }
}